package ru.storeva.buildlogic.tenant

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

abstract class GenerateIosXcconfigTask : DefaultTask() {

    @get:InputFile
    abstract val tenantFile: RegularFileProperty

    @get:Input
    abstract val environment: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val config = TenantConfigLoader.load(tenantFile.get().asFile)
        val env = environment.get()

        val file = outputFile.get().asFile
        file.parentFile.mkdirs()

        file.writeText(
            buildString {
                appendLine("// Generated by storeva.tenant Gradle plugin")
                appendLine("// Do not edit manually")
                appendLine()
                appendLine("TENANT_ID = ${config.id}")
                appendLine("APP_DISPLAY_NAME = ${config.app.displayName}")
                appendLine("PRODUCT_BUNDLE_IDENTIFIER = ${config.app.iosBundleId}")
                appendLine("API_BASE_URL = ${config.apiBaseUrl(env).escapeXcconfigValue()}")
                appendLine("DEEPLINK_HOST = ${config.app.deeplinkHost.orEmpty()}")
                appendLine()
                appendLine("TENANT_PRIMARY_COLOR = ${config.branding.primaryColor}")
                appendLine("TENANT_ACCENT_COLOR = ${config.branding.accentColor}")
                appendLine("TENANT_BACKGROUND_COLOR = ${config.branding.backgroundColor}")
            },
        )
    }
}

private fun String.escapeXcconfigValue(): String {
    return replace("://", ":/$()/")
}